### ISSUE TITLE
Паттерны проектирования

### ISSUE THREAD

**Issue by asagynbaev** [holokinovoro/mini-music-api#1]
Интересная реализциая, просьба рассмотреть возможность использования паттерна "Репозиторий".

Подробнее: https://learn.microsoft.com/ru-ru/aspnet/mvc/overview/older-versions/getting-started-with-ef-5-using-mvc-4/implementing-the-repository-and-unit-of-work-patterns-in-an-asp-net-mvc-application

**Comment by holokinovoro** [comment]
Спасибо за комментарий, обязательно рассмотрю)

**Comment by holokinovoro** [comment]
Конечно отвечаю очень поздно, но в проекте у меня уже применен паттерн репозитория. Считал что где то чего то упустил, однако в проекте у меня все соответствует. Может быть вы увидели некий пробел? Буду рад если укажете на это

**Comment by asagynbaev** [comment]
просьба связаться со мной, tg: @azimbek_eth

as@mydatacoin.io

**Comment by asagynbaev** [comment]
#1 closed
